---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: pamela-web          
  name: pamela-web
  selfLink: /apis/apps/v1/namespaces/default/deployments/pamela-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pamela-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: comprasa2-web
    spec:
      containers:
      - image: ghcr.io/br-engmanager/pamela-web:1.0.0
        imagePullPolicy: IfNotPresent
        name: comprasa2-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: regsecrethubeng
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pamela-web
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pamela-web
